[package]
name = "libweb"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
libnetclient = { path = "../libnetclient" }
userlib = { path = "../userlib" }
embedded-io = { version = "0.7", default-features = false }
embedded-tls = { version = "0.19", default-features = false, features = ["rustpki", "rsa"] }
rand_core = { version = "0.6", default-features = false }
p256 = { version = "0.13", default-features = false, features = ["ecdsa"] }

