use anyhow::Result;
use clap::{Parser, Subcommand};
use mkzfs::ZfsImageBuilder;
use std::fs;
use std::path::PathBuf;

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Command::Create { output, size } => {
            let builder = ZfsImageBuilder::new(size as usize)?;
            builder.format()?;
            builder.flush_to(&output)?;
            println!("mkzfs: created {} ({} bytes)", output.display(), size);
        }
        Command::ImportRootfs {
            output,
            rootfs_bundle,
        } => {
            let builder = ZfsImageBuilder::new(64 * 1024 * 1024)?;
            builder.format()?;
            let bundle_data = fs::read(&rootfs_bundle)?;
            builder.import_bundle(&bundle_data)?;
            builder.flush_to(&output)?;
            println!("mkzfs: created {} with bootstrap rootfs", output.display());
        }
        Command::InjectPasswd { image, user, hash } => {
            let builder = ZfsImageBuilder::load(&image)?;
            builder.ensure_system_dirs()?;
            builder.write_passwd(&user, &hash)?;
            builder.flush_to(&image)?;
            println!("mkzfs: updated {} with /etc/passwd entry", image.display());
        }
    }
    Ok(())
}

#[derive(Parser)]
#[command(author, version, about = "ZeroFS formatting tool")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Create an empty ZeroFS image with the given size (bytes)
    Create {
        #[arg(long)]
        output: PathBuf,
        #[arg(long, default_value = "33554432")]
        size: u64,
    },
    /// Populate a ZeroFS image from the rootfs bundle generated by xtask
    ImportRootfs {
        #[arg(long)]
        output: PathBuf,
        #[arg(long)]
        rootfs_bundle: PathBuf,
    },
    /// Add or update an administrator account in /etc/passwd inside the image
    InjectPasswd {
        #[arg(long)]
        image: PathBuf,
        #[arg(long)]
        user: String,
        #[arg(long)]
        hash: String,
    },
}
