[package]
name = "zero-service-controller"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["rlib"]

[[bin]]
name = "zero-service-controller"
path = "src/bin/main.rs"

[dependencies]
zero-abi = { path = "../../libs/abi" }
log = { workspace = true }
userlib = { path = "../../userland/userlib" }
heapless = { version = "0.8", default-features = false }
itoa = "1"
spin = { workspace = true }

useralloc = { path = "../../userland/useralloc" }
